//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPWA_PMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_errores
    {
        public System.Guid id_error { get; set; }
        public string aplicacion { get; set; }
        public string host { get; set; }
        public string tipo { get; set; }
        public string origen { get; set; }
        public string mensage { get; set; }
        public string usuario { get; set; }
        public int cod_status { get; set; }
        public System.DateTime time_utc { get; set; }
        public int secuencia { get; set; }
        public string all_xml { get; set; }
    }
}
