//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPWA_PMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        public System.Guid id_direccion { get; set; }
        public System.Guid id_cliente { get; set; }
        public short id_municipio { get; set; }
        public short id_entidad { get; set; }
        public string codigo_postal { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public string no_interior { get; set; }
        public string no_exterior { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual entidad entidad { get; set; }
        public virtual municipio municipio { get; set; }
    }
}
