//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPWA_PMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.factura_articulo = new HashSet<factura_articulo>();
            this.factura_venta = new HashSet<factura_venta>();
        }
    
        public long id_factura { get; set; }
        public System.Guid id_cliente { get; set; }
        public System.DateTime fecha_remision { get; set; }
        public string uso_cfdi { get; set; }
        public string forma_pago { get; set; }
        public string metodo_pago { get; set; }
        public string tipo_comprobante { get; set; }
        public string exportaciones { get; set; }
        public Nullable<short> id_estatus { get; set; }
        public string factura_xml { get; set; }
        public Nullable<System.Guid> uuid_sat { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual estatus estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_articulo> factura_articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_venta> factura_venta { get; set; }
    }
}
