//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPWA_PMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class forma_pago
    {
        public string id { get; set; }
        public string descripcion { get; set; }
        public string bancarizado { get; set; }
        public string num_operacion { get; set; }
        public string rfc_ordenante { get; set; }
        public string cuenta_ordenante { get; set; }
        public string rfc_beneficiario { get; set; }
        public string cuenta_beneficiario { get; set; }
        public string tipo_pago { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
    }
}
