//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPWA_PMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generacion_codigos
    {
        public long id_gencode { get; set; }
        public Nullable<decimal> cod_barras { get; set; }
        public Nullable<decimal> cod_pesable { get; set; }
        public Nullable<decimal> cod_inpesable { get; set; }
    }
}
