//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPWA_PMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_articulo
    {
        public string cod_barras { get; set; }
        public System.DateTime fecha_inicial_inv { get; set; }
        public System.DateTime fecha_ultima_act { get; set; }
        public decimal inventario_ini { get; set; }
        public decimal entradas { get; set; }
        public decimal compras { get; set; }
        public decimal salidas { get; set; }
        public decimal ventas { get; set; }
        public decimal stock_actual { get; set; }
    
        public virtual articulo articulo { get; set; }
    }
}
