//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPWA_PMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salida_articulo
    {
        public System.Guid id_salida { get; set; }
        public string cod_barras { get; set; }
        public decimal cant_sal { get; set; }
        public decimal cant_pza { get; set; }
        public decimal cant_reg { get; set; }
        public decimal costo { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual salida salida { get; set; }
    }
}
